function flobii(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',ac='.cache.html',_='/',Rb='08D354A50B5BC543CB193B4586B471E0',Sb='161CDEE2E14DA91C79C7F6170AAC685E',Tb='2310B1CBA0A0C9C418E498C4D1C46CC9',Ub='34566C67498FDBD0B9F9F54FA27CF407',Vb='42DD3E9D781CDD510A6756D9D9AEE8E3',Wb='839FF020B55F1644B50C056A387A05A5',_b=':',ob='::',lc='<script defer="defer">flobii.onInjectionDone(\'flobii\')<\/script>',hb='<script id="',rb='=',$='?',Xb='A896C9B69A50ADF2236FC01DFF2B8070',Yb='BE8862FF166217183B19FA491EBD87E1',Db='BackCompat',tb='Bad handler "',Zb='CB4A030432C3CF11AEA51F15201F1545',Cb='CSS1Compat',kc='DOMContentLoaded',$b='FCFCD38B1DFA273DA1BBCA74A104F9A2',ic='GwtFacebook.css',jb='SCRIPT',gb='__gwt_marker_flobii',kb='base',cb='baseUrl',T='begin',S='bootstrap',jc='cbg_button.css',bb='clear.cache.gif',Bb='compat.mode',qb='content',Y='end',Q='flobii',eb='flobii.nocache.js',nb='flobii::',Lb='gecko',Mb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',hc='gwt/standard/mosaic.css',bc='gwt/standard/standard.css',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',gc='head',Pb='hosted.html?flobii',fc='href',Kb='ie6',Jb='ie8',xb='iframe',ab='img',yb="javascript:''",cc='link',Ob='loadExternalRefs',lb='meta',Ab='moduleRequested',X='moduleStartup',Ib='msie',mb='name',Fb='opera',zb='position:absolute;width:0;height:0;border:none',dc='rel',Hb='safari',db='script',Qb='selectingPermutation',R='startup',ec='stylesheet',fb='undefined',Nb='unknown',Eb='user.agent',Gb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}flobii=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){return document.compatMode==Cb?Cb:Db};u[Bb]={BackCompat:0,CSS1Compat:1};v[Eb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Fb)!=-1){return Fb}else if(b.indexOf(Gb)!=-1){return Hb}else if(b.indexOf(Ib)!=-1){if(document.documentMode>=8){return Jb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Kb}}}}else if(b.indexOf(Lb)!=-1){return Mb}return Nb};u[Eb]={gecko1_8:0,ie6:1,ie8:2,opera:3,safari:4};flobii.onScriptLoad=function(){if(I){q=true;B()}};flobii.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Ob,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Pb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Qb});if(!A()){try{G([Db,Jb],Rb);G([Db,Fb],Sb);G([Cb,Fb],Tb);G([Db,Hb],Ub);G([Cb,Kb],Vb);G([Db,Kb],Wb);G([Cb,Jb],Xb);G([Db,Mb],Yb);G([Cb,Hb],Zb);G([Cb,Mb],$b);K=w[H(Bb)][H(Eb)];var M=K.indexOf(_b);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+ac}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[bc]){var a=m.createElement(cc);__gwt_stylesLoaded[bc]=a;a.setAttribute(dc,ec);a.setAttribute(fc,s+bc);m.getElementsByTagName(gc)[0].appendChild(a)}if(!__gwt_stylesLoaded[hc]){var a=m.createElement(cc);__gwt_stylesLoaded[hc]=a;a.setAttribute(dc,ec);a.setAttribute(fc,s+hc);m.getElementsByTagName(gc)[0].appendChild(a)}if(!__gwt_stylesLoaded[ic]){var a=m.createElement(cc);__gwt_stylesLoaded[ic]=a;a.setAttribute(dc,ec);a.setAttribute(fc,s+ic);m.getElementsByTagName(gc)[0].appendChild(a)}if(!__gwt_stylesLoaded[jc]){var a=m.createElement(cc);__gwt_stylesLoaded[jc]=a;a.setAttribute(dc,ec);a.setAttribute(fc,s+jc);m.getElementsByTagName(gc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(kc,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(kc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Ob,millis:(new Date).getTime(),type:T});m.write(lc)}
flobii();